const form = document.getElementById("documentForm");
const preview = document.getElementById("documentPreview");
const editable = document.getElementById("editableDocument");
const emptyState = document.getElementById("emptyState");
const generateBtn = document.getElementById("generateBtn");
const editBtn = document.getElementById("editBtn");
const txtBtn = document.getElementById("txtBtn");
const printBtn = document.getElementById("printBtn");
let generatedText = "";
let isEditing = false;

function escapeHtml(value) {
  return value.replace(/[&<>"']/g, char => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;"
  }[char]));
}

function formatDate(value) {
  if (!value) return "";
  return new Date(value + "T00:00:00").toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric"
  });
}

function createDraft(type, parties, terms, date) {
  const partyList = parties.split(",").map(x => x.trim()).filter(Boolean);
  const termList = terms.split(";").map(x => x.trim()).filter(Boolean);

  let text = `${type.toUpperCase()}\n\n`;
  text += `Effective Date: ${date}\n`;
  text += `Parties: ${partyList.join(" | ")}\n\n`;
  text += `1. PURPOSE\n\n`;
  text += `This ${type.toLowerCase()} is entered into by the parties identified above and is intended to document the terms agreed between them.\n\n`;
  text += `2. PARTIES\n\n`;
  text += `${partyList.length ? partyList.map((p, i) => `${i + 1}. ${p}`).join("\n") : "The parties identified by the user."}\n\n`;
  text += `3. TERMS AND CONDITIONS\n\n`;
  termList.forEach((term, i) => { text += `${i + 1}. ${term}\n`; });
  text += `\n4. EFFECTIVE DATE\n\n`;
  text += `This document takes effect on ${date}.\n\n`;
  text += `5. GENERAL PROVISIONS\n\n`;
  text += `The parties should review this draft carefully and make any required amendments before signing. Any applicable governing law, notices, signatures, and other provisions should be added as appropriate to the specific transaction.\n\n`;
  text += `SIGNATURES\n\n`;
  partyList.forEach(p => {
    text += `______________________________\n${p}\nDate: _________________________\n\n`;
  });
  return text;
}

function renderDocument(text) {
  const lines = text.split("\n");
  const title = escapeHtml(lines.shift() || "Legal Document");
  const html = lines.map(line => {
    if (!line.trim()) return "<div class='spacer'></div>";
    if (/^\d+\.\s[A-Z][A-Z\s]+$/.test(line.trim())) {
      return `<h2>${escapeHtml(line)}</h2>`;
    }
    if (/^\d+\.\s/.test(line.trim())) {
      return `<p>${escapeHtml(line)}</p>`;
    }
    return `<p>${escapeHtml(line)}</p>`;
  }).join("");
  preview.innerHTML = `<h1>${title}</h1><div class="doc-meta">Generated by LegalEase · Draft for review</div>${html}`;
}

form.addEventListener("submit", (event) => {
  event.preventDefault();

  const type = document.getElementById("documentType").value;
  const parties = document.getElementById("parties").value.trim();
  const terms = document.getElementById("terms").value.trim();
  const date = formatDate(document.getElementById("effectiveDate").value);

  if (!parties || !terms || !date) return;

  generateBtn.classList.add("loading");
  generateBtn.innerHTML = "Generating…";

  setTimeout(() => {
    generatedText = createDraft(type, parties, terms, date);
    renderDocument(generatedText);
    emptyState.classList.add("hidden");
    preview.classList.remove("hidden");
    editable.classList.add("hidden");
    editBtn.disabled = false;
    txtBtn.disabled = false;
    printBtn.disabled = false;
    isEditing = false;

    generateBtn.classList.remove("loading");
    generateBtn.innerHTML = "<span>✦</span> Generate Document";
    document.getElementById("preview").scrollIntoView({ behavior: "smooth", block: "start" });
  }, 650);
});

editBtn.addEventListener("click", () => {
  if (!generatedText) return;
  if (!isEditing) {
    editable.value = generatedText;
    preview.classList.add("hidden");
    editable.classList.remove("hidden");
    editBtn.textContent = "✓ Save";
    isEditing = true;
  } else {
    generatedText = editable.value;
    renderDocument(generatedText);
    editable.classList.add("hidden");
    preview.classList.remove("hidden");
    editBtn.textContent = "✎ Edit";
    isEditing = false;
  }
});

txtBtn.addEventListener("click", () => {
  const blob = new Blob([generatedText], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "LegalEase-document.txt";
  link.click();
  URL.revokeObjectURL(url);
});

printBtn.addEventListener("click", () => {
  if (isEditing) {
    generatedText = editable.value;
    renderDocument(generatedText);
    editable.classList.add("hidden");
    preview.classList.remove("hidden");
    editBtn.textContent = "✎ Edit";
    isEditing = false;
  }
  window.print();
});

window.addEventListener("beforeprint", () => {
  document.body.classList.add("printing");
});

window.addEventListener("afterprint", () => {
  document.body.classList.remove("printing");
});

